services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    # container_name: homepage
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ${CONFIG_ROOT:-.}/homepage:/app/config
      - ${DATA_ROOT}:/data
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ${CONFIG_ROOT:-.}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: always
    privileged: true
    network_mode: host

  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ${CONFIG_ROOT:-.}/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
