services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    # container_name: homepage
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ${CONFIG_ROOT:-.}/homepage:/app/config
      - ${DATA_ROOT}:/data
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 3001:8123
    volumes:
      - ${CONFIG_ROOT:-.}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
