include:
  - stacks/home/docker-compose.yml
  - stacks/home-automation/docker-compose.yml
  - stacks/media/docker-compose.yml
  - stacks/arr/docker-compose.yml


networks:
  default:
    name: homelab-nas
